name: Build and Push Python payment Service

on:
  push:
    paths:
      - 'payment/**'
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: payment
  GIT_TAG: v1.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # ✅ Setup gcloud
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # ✅ Configure Docker for Artifact Registry
      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # ✅ Build Python service Docker image
      - name: Build Docker Image
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/solar-idea-466712-c7/tierdemo/${{ env.IMAGE_NAME }}:${{ env.GIT_TAG }} \
            ./payment

      # ✅ Push the image
      - name: Push Docker Image
        run: |
          docker push \
            us-central1-docker.pkg.dev/solar-idea-466712-c7/tierdemo/${{ env.IMAGE_NAME }}:${{ env.GIT_TAG }}
